### ISSUE TITLE
Event page: left action

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#10]
When on the event page, 'left' should immediately take the user back to the main navigation. At the moment it highlights the 'return' icon and then the user must select 'OK' to confirm it. Other apps (such as Netflix) keep it simple, and the user just presses left and immediately returns.

(Note: the focus must of course be on the left for this to work - if they are on a screen where they have scrolled to the right, they need to return to the start).

**Comment by CSeal** [comment]
the estimate is about 30h

**Comment by mark-weber** [comment]
Do you mean 30h or was it meant to be 3h? 30h would be several days worth of work.

**Comment by CSeal** [comment]
sorry, my mistake. of course 3h

**Comment by CSeal** [comment]
done

**Comment by tomdyson** [comment]
@CSeal can you please link to the PR / commit?
