### ISSUE TITLE
Intermittent playback bugs

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#112]
These may have coincided with leaving the screensaver. They don't seem to reoccur on the times that they initially occurred on.
(first 9.10, and second 28.51
![IMG_1633](https://user-images.githubusercontent.com/84398423/144421846-8a8a7acd-ffc5-4f7a-9bb5-cb3d9fa02810.png)
![IMG_1634](https://user-images.githubusercontent.com/84398423/144421905-15309ea3-a36a-4cda-8b01-1d32c1dd5ed7.png)
)

**Comment by CSeal** [comment]
the error is not reproducible
