### ISSUE TITLE
Pause / play buttons don't work on remote control

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#113]
I can use select to then choose pause/play, but pause/play button itself does not work

**Comment by CSeal** [comment]
@mark-weber could you be more specific in this case? or provide an example of this bug or behavior as a video demo for example. It will be useful for solving the problem

**Comment by mark-weber** [comment]
BUG: When watching a video, nothing happens if you press the play/pause button on the remote except to bring up on-screen the video scrub line (e.g. it neither plays or resumes playing).

ENHANCEMENT: It would be nice that the remote's play button will trigger the 'watch now' action on the home screen of an event.

**Comment by CSeal** [comment]
we can do both of these issues. It will take about 3-4 hours with testing and debugging

**Comment by CSeal** [comment]
estimate 1,5 hours

**Comment by CSeal** [comment]
started working,
