### ISSUE TITLE
Checking if item is accessible via PPV for non-subscribers: 14th Jan

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#141]

**Comment by CSeal** [comment]
We had a chat with Viktor, as for now, the information that comes as the response for his endpoint is hard for me to link to the event details I receive from Prismic. We will continue our discussion on Monday to decide whether it would be better to amend his endpoint or if I should do some additional development on the TV app side.

There is also a question around the time period during which the PPV should be available for users to watch, it will also have an impact on implementation. So we will need more time on figuring out the approach for this.

And just to clarify, if we understand this correctly:

- the main page has rails with PPV events for the user who is not subscribed.
- if the user is subscribed, there is no rail with PPV as all events are available
- the unsubscribed user has access only to purchased PPV events and can view them

Is there anything we missed?

**Comment by mark-weber** [comment]
>> the main page has rails with PPV events for the user who is not subscribed.
Yes

>> if the user is subscribed, there is no rail with PPV as all events are available
Yes

>>the unsubscribed user has access only to purchased PPV events and can view them
They will only be able to watch the full video for purchased PPV, but can view trailers & info about all other items

**Comment by YuliyaDmuytrus** [comment]
We will need additional development on this feature, once we have final approval from where we should retrieve the digital event availability from.
