### ISSUE TITLE
Return button functionality and side menu

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#152]
The implementation of the 'return' button in our app is quite random and not very predictable. NetFlix appear to have a much more sensible implementation of it., which is the one we should follow:

- Rule 1: On the home screen, return button opens up the side-nav menu
- Rule 2: The return button **does not exit the app** - only the home button does that
- Rule 3: The return button on an item page will return the user back to the home screen.

In our app, the return button exits the app from the home screen which it should not do.
In our app, if you move through the menu sections, and then press the return button, it takes you back through the sections of the menu (but without changing the highlights) that you've just navigated through. This is very confusing.
I think the problems I was experiencing with the nav are related to our use of the return button.
If we copied the simpler rules from Netflix it would make it more usable and simpler.

**Comment by YuliyaDmuytrus** [comment]
Jira ticket https://jira.atlassian.roh.org.uk/browse/RD-7535

**Comment by YuliyaDmuytrus** [comment]
The correct description of task here:
The implementation of the 'return' button is problematic.
If pressed then it moves the user through the side-navigation.
We should follow the BBC iPlayer approach:

Pressing 'return' when on the main screen opens up the side nav
Pressing 'return' when on the side nav opens up the modal to confirm app exit
The return button should not move the user through the side nav.
