### ISSUE TITLE
4k and other variants of fireTV not permitting installation of test version

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#19]
Report from Steve Wadey of FireTV sticks refusing to permit installation of app from Amazon.com:

For reference, the two Fire TV sticks I have are:

- Standard (1st generation)

Purchased 2016
Software version 5.2.8.0 (668694820)
Fire TV Home Version 6242057.1

- 4K

Purchased 2021
Software version Fire OS 6.2.8.1 (NS6281/3385)
Fire TV Home Version 6330044.1

**Comment by mark-weber** [comment]
![image001](https://user-images.githubusercontent.com/84398423/132829282-be5f8ae2-4c28-4e0e-8dfd-502ab48806d8.png)

**Comment by CSeal** [comment]
the estimate is about 4h

**Comment by CSeal** [comment]
done
