### ISSUE TITLE
App sometimes starts in unpaired mode

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#23]
Sometimes when I start the app on FireTV it defaults to the unpaired 'get started' screen, and then on selecting this option it goes to the pairing screen. After 3-4 seconds it then switches to subscribed mode.
Can we do the subscription check on startup so that we avoid this?

**Comment by CSeal** [comment]
the estimate is about 3h

**Comment by CSeal** [comment]
done

**Comment by tomdyson** [comment]
> done

@CSeal please link to the PR or commit.
