### ISSUE TITLE
Retrieve HLS URLs for Bitmovin player from Prismic API

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#32]
URLs to be added to Prismic for each event.
URLs to be added this week.

**Comment by mark-weber** [comment]
Oleks to share links

**Comment by zinevych** [comment]
Hi @mark-weber 
For now we have these 2 streams:
https://s3.eu-west-1.amazonaws.com/streamv2.stagev2.website.roh.org.uk/12339/manifest.m3u8
https://s3.eu-west-1.amazonaws.com/streamv2.stagev2.website.roh.org.uk/90001/manifest.m3u8

**Comment by sinewave440hz** [comment]
Hi, which titles are these for btw? (excuse my cultural ignorance ;) )

**Comment by mark-weber** [comment]
URL for dummy video: https://video-ingestor-output-bucket.s3.eu-west-1.amazonaws.com/6565/manifest.m3u8

**Comment by sinewave440hz** [comment]
The expected structure from Prismic contains an array of videos. In each video item there is an isBroken boolean that needs checking, if true, that video's id can be used to build the url link based on this: ` https://roh-stagev2.global.ssl.fastly.net/api/video-source?id=`.

**Comment by sinewave440hz** [comment]
Draft PR up, got as far as I can for now. Shows basic logic, need 1) info on how to get the videos data in from prismic and 2) a couple of test videos

**Comment by sinewave440hz** [comment]
As I understand it, there can be several videos available for each event. How do we decide which one to choose? I've asked Maksym but not sure if he's the right person to ask.

**Comment by sinewave440hz** [comment]
Maksym was indeed the right person to ask :) We should choose the video with type "performance". The other video types available that we can fetch if necessary, later are "trailer" and "behind the scenes". Also, the response from the link that is contained in the "performance" video data will return both dash and hls links.
