### ISSUE TITLE
PIN number not appearing

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#33]
Since the 4k update release, the PIN number is not appearing for some users on new downloads of the app.

**Comment by CSeal** [comment]
screen with pin is working. https://prnt.sc/1tcltyt . I guess it is related to IP access. If you get a 403 error(forbidden) you will not get the device id from the backend for showing.

**Comment by mark-weber** [comment]
If Pin is not retrieved by App, can we display 'Sorry, pin not found' where we would place the PIN number.
