### ISSUE TITLE
Checking if user is subscriber or not: 10th Jan

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#40]
We need to check if the user is a subscriber or not
- When pairing the app
- When in unsubscribed mode (on a timer + when user triggers events such as looking at a performance, going to how to watch screen, etc)

**Comment by CSeal** [comment]
we do not do it When pairing the app because we will do it when a user will want to watch a performance video. so he can only watch vide if he is subscribing or going to how to watch modal screen

**Comment by mark-weber** [comment]
Waiting on the purchase journey

**Comment by CSeal** [comment]
Hello @mark-weber ,
I have a couple of questions about this task.
We have implemented the check for subscribed/unsubscribed mode has been already implemented.
What additional work should we include here? Should we just test the state of the TV app after the successful purchase of the stream?

Or is there a new feature required?

**Comment by mark-weber** [comment]
This should be all, thanks.
