### ISSUE TITLE
Update video error to include video URL

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#59]

**Comment by mark-weber** [comment]
To open a default error message which says: 

Sorry, an error has occurred
error code: code [sentry code or some identifiable reference]
Please restart your app.

**Comment by CSeal** [comment]
@mark-weber I am able to show only these errors ([Native Bitmovin Errors](https://bitmovin.com/docs/encoding/api-reference/help))
Does it work for you?

**Comment by mark-weber** [comment]
Happy with any we can get.

**Comment by CSeal** [comment]
started working

**Comment by CSeal** [comment]
Done
