### ISSUE TITLE
Styling for subtitles: 5th Jan

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#62]

**Comment by mark-weber** [comment]
Bitmovin weren't able to help. Allan to try bespoke solution.

**Comment by mark-weber** [comment]
We shall implement solution as found, come back to in the future for further improvements.

**Comment by mark-weber** [comment]
@CSeal please check, and if OK, close this issue.

**Comment by CSeal** [comment]
Hi @mark-weber, are you happy with how subtitles work? May I close this issue?

**Comment by mark-weber** [comment]
@CSeal please provide name of video which includes subtitles so I can test it

**Comment by YuliyaDmuytrus** [comment]
Hi, @mark-weber , could you please try La Boheme?
It has the full-length video with subtitles

**Comment by YuliyaDmuytrus** [comment]
Many thanks, Mark.
Closing this issue.
