### ISSUE TITLE
White screen appears on loading: need loading screen

### ISSUE THREAD

**Issue by mark-weber** [royaloperahouse/stream-tv-app#7]
When launching the TV app on the fireStick (lite version), there is a white screen that appears 2-3 seconds before the app. 
We should have a loading screen to replace this.

**Comment by tomdyson** [comment]
Some possibly relevant discussion here: https://stackoverflow.com/questions/51707841/android-tv-app-shows-white-screen

**Comment by tomdyson** [comment]
See also https://reactnative.dev/docs/building-for-tv#build-changes which suggests that 

https://github.com/royaloperahouse/stream-tv-app/blob/main/android/app/src/main/AndroidManifest.xml#L30

should be `android.intent.category.LEANBACK_LAUNCHER` rather than `android.intent.category.LAUNCHER`.

**Comment by CSeal** [comment]
the estimate is about 5h
Amazon has an in-house solution for it
need a design for this splash screen;

**Comment by mark-weber** [comment]
@CSeal there's a loading screen you can use on this Figma file: https://www.figma.com/file/CDpPSEGMegUbDwguymGFmQ/ROH-05%3A-TV-App?node-id=803%3A14636
(top left corner)
